# Generated by Django 3.2.5 on 2021-07-05 00:22

import aulas.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ano Escolar',
                'verbose_name_plural': 'Anos Escolares',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OutroCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Outro Curso',
                'verbose_name_plural': 'Outros Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=60)),
                ('dt_nascimento', models.DateField(db_index=True, verbose_name='Data Nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[aulas.functions.validate_CPF], verbose_name='CPF')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='E-Mail')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=250)),
                ('escola', models.CharField(max_length=250)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('nome_responsavel1', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Responsável 1')),
                ('grau_parentesco1', models.CharField(blank=True, max_length=60, null=True, verbose_name='Grau do Parentesco 1')),
                ('celular_1', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular do Responsável 1')),
                ('nome_responsavel2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Responsável 2')),
                ('grau_parentesco2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Grau do Parentesco 2')),
                ('celular_2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular do Responsável 2')),
                ('ja_cursou', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='O(A) aluno(a) já frequentou algum curso na Oficina Escola ou nos Pontos de Cultura?')),
                ('retorno_presencial', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Mediante o retorno das aulas presenciais seguindo todos os protocolos de segurança da vigilância sanitária, o aluno está autorizado a frequentá-las?')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('anoescolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aulas.anoescolar', verbose_name='Ano Escolar')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aulas.curso', verbose_name='Curso Desejado')),
                ('outro_curso', models.ManyToManyField(blank=True, to='aulas.OutroCurso', verbose_name='Quais outros cursos você gostaria de ver disponíveis na Oficina Escola de Artes e nos Pontos de Cultura?')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
