# Generated by Django 3.2.5 on 2021-07-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_instrutor_turma_turma_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrutor',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Instrutores'},
        ),
        migrations.AlterModelOptions(
            name='turma_aluno',
            options={'ordering': ['turma', 'aluno'], 'verbose_name': 'Turma/Alunos', 'verbose_name_plural': 'Turmas/Alunos'},
        ),
        migrations.AlterUniqueTogether(
            name='turma_aluno',
            unique_together={('turma', 'aluno')},
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_google', models.CharField(max_length=250, verbose_name='E-Mail no Google')),
                ('ativo', models.BooleanField(default=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aulas.candidato')),
            ],
            options={
                'ordering': ['candidato'],
            },
        ),
    ]
